### ISSUE TITLE
citation problem

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#48] opened 2024-07-29 16:39 UTC
https://github.com/egouldo/ManyAnalysts/blob/91ca56a15ab2630054e7391b9b90a2dc974feb65/index.qmd#L2248

For some reason, the citation of Shinichi's paper is rendering as "… deviation scores (Shinichi Nakagawa et al. 2022).”

We looked into this before and couldn't figure out why it is spitting out "Shinichi Nakagawa" instead of just "Nakagawa"

**Comment by egouldo** [comment] 2024-07-31 03:36
This is a duplicate of issue #29 closing this issue.

**Closed as completed by egouldo** 2024-07-31 03:36 UTC
